#override defaults for dev
version: "3.7"

services:
  app_server:
    build: .
    links:
      - mysql
    ports:
      - 8000:8080
    environment:
      - DATABASE_URL=mysql://root:root@mysql:3306/prod_test
      - APP_URL=http://localhost:8000
      - APP_SECRET=8583a6ff63c5894a3195331701749943
      - APP_ENV=dev
      - INSTANCE_ID=
      - SHOPWARE_ES_ENABLED=0
      - SHOPWARE_ES_HOSTS=elasticsearch:9200
      - SHOPWARE_ES_INDEXING_ENABLED=0
      - SHOPWARE_ES_INDEX_PREFIX=
      - SHOPWARE_HTTP_CACHE_ENABLED=0
      - SHOPWARE_HTTP_DEFAULT_TTL=
    volumes:
      - "./config/jwt:/sw6/config/jwt"
      - "./public:/sw6/public"
      - "./bin:/sw6/bin"
      - "./src:/sw6/src"
      - "./var:/sw6/var"
      #- "./vendor:/sw6/vendor"

  mysql:
    image: mysql:5.7
    tmpfs:
      - /var/lib/mysql:uid=999,gid=999
    environment:
      - MYSQL_ROOT_PASSWORD=root

  adminer:
    image: adminer
    restart: always
    links:
      - mysql
    environment:
      - ADMINER_DESIGN=pepa-linha
    ports:
      - 8888:8080
